trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '*'
    exclude:
      - '*/.azuredevops/pull_request_template/*'
      - docs/*
      - '*/README.md'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build
    variables:
      - template: 'variables/rkt-data-adf-generic.yml'
        parameters:
          environmentShortName: dev
    jobs:
      - template: templates/build.yml

  - stage: DeployDev
    dependsOn: Build
    displayName: RKT-DATA-DEV
    variables:
      - template: 'variables/rkt-data-adf-generic.yml'
        parameters:
          environmentShortName: dev
    jobs:
      - template: templates/deploy.yml
        parameters:
          environmentName: RKT-DATA-DEV
          azureServiceConnection: rkt-ado-sc

  - stage: DeployPrd
    dependsOn: DeployDev
    displayName: RKT-DATA-PRD
    variables:
      - template: 'variables/rkt-data-adf-generic.yml'
        parameters:
          environmentShortName: prd
    jobs:
      - template: templates/deploy.yml
        parameters:
          environmentName: RKT-DATA-PRD
          azureServiceConnection: rkt-ado-sc
