parameters:
  - name: skipPublish
    type: boolean
    default: true

jobs:
# Validate and Package Azure Infra
- job: PublishInfrastructureArtifacts
  displayName: Publish Infrastructure Artifacts
  pool:
    vmImage: ubuntu-latest
  steps:
    # Validate Bicep
    - task: PowerShell@2
      displayName: Validate Infrastructure Bicep
      inputs:
        targetType: inline
        script: 'az bicep build --file main.bicep'
        workingDirectory: '$(Build.SourcesDirectory)/env'

    # Publish the Infrastructure artifacts.
    - task: PublishPipelineArtifact@1
      condition: and(succeeded(), eq('${{ parameters.skipPublish }}', 'true'))
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/env'
        artifact: 'azure'
        publishLocation: 'pipeline'
